name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: yarn install
      - run: yarn test
      - run: yarn lint
  release:
    name: Release
    needs: test
    if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: yarn
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
