name: Update Tags

on:
  release:
    types:
      - created
      - published
      - edited

jobs:
  action-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: false
          prefer_branch_releases: false
          token: ${{ github.token }}
